version: '{build}'
image: Visual Studio 2019
skip_tags: true
before_build:
- cmd: cd build
build_script:
- cmd: build.bat
artifacts:
- path: artifacts/*.nupkg
  name: nupkg
  type: File
deploy:
- provider: NuGet
  name: NuGet
  api_key:
    secure: VdijQhbe0VWQjwJjKkVqZpvUlMn7DQF040dV5UXpo7WZ8oj54ypNBIntRu50Suv9
  artifact: nupkg
  on:
    branch: master
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  symbol_server: https://www.myget.org/F/dittodhole/symbols/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
  artifact: nupkg
